### ISSUE TITLE
Annual Iridium Go  Checklist

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#630]
- [ ] Follow [this guide](https://apollosat.com/docs/iridium-go-pre-trip-checklist/) to check the operation of the Iridium Go
- [ ] Subscription current
- [ ] Subscription renewal scheduled
- [ ] SOP up to date (numbers, passwords, procedures)
- [ ] Supporting software on Ships Tablet is updated and functioning

**Comment by smr547** [comment]
@Christopher-w-green will be interested in this issue (Chris, I think you have covered most of these things)

**Comment by pcbaston** [comment]
The IridiumGO is a simple modem interface for smartphones using satellite network when out of normal phone range. 
I tested the unit and it boots up correctly. I tried an email using the app with no luck. I tried voice (phonecall) and received an unavailable number response. 
Assuming the service is not activated!
Where is the info stating the service is current(paid for)?

**Comment by smr547** [comment]
Hi @pcbaston 

Both Chris Green (@Christopher-w-green ) and I have tested voice and SMS messaging on Iridium Go and found it to work well both with the iPhone and Android/Samsung Apps. Tests have also been performed with Predict Wind (mainly downloading data) -- @pauljones17 and @PSARN (Peter Lucey) were involved in these test.

I wonder what's changed? 

It also raised the point that I have no record of our Iridium Go subscription.  Perhaps it has expired and needs to be renewed.

Can someone remind me please. @delcosta or @pjwain might have a record.

**Comment by pjwain** [comment]
Hi Steve,
Sam DL arranged a monthly Go Unlimited subscription in October. Invoices
attached.
Regards,
Peter.

**Comment by Christopher-w-green** [comment]
There's nothing wrong. IridiumGo just needed a reboot, that's all. Happened the other day too when M Martin was on board. Peter Wain and I updated the software on the Iridium a couple of weeks ago, but it doesn't seem super stable and seems to lose its satellite link if it's sitting there for a long time.
So first troublshoot- try turning it iff and on again.

**Comment by PSARN** [comment]
Iridium Go working well with predict wind while tested last week on board Namadgi. Only issue was when downloading ocean currents time-out occurred, (I don't think CORC purchased this option-nor is it generally necessary) however by reducing the grib file area ocean currents download can be achieved. Best if ocean currents are downloaded separately and prior to weather routing. Hope this is clear.
Peter

From: pjwain ***@***.***>
Reply to: CanberraOceanRacingClub/namadgi3 ***@***.***>
Date: Wednesday, 14 December 2022 at 12:50
To: CanberraOceanRacingClub/namadgi3 ***@***.***>
Cc: ***@***.***" ***@***.***>, Mention ***@***.***>
Subject: Re: [CanberraOceanRacingClub/namadgi3] Annual Iridium Go Checklist (Issue #630)

Hi Steve,
Sam DL arranged a monthly Go Unlimited subscription in October. Invoices
attached.
Regards,
Peter.

**Comment by smr547** [comment]
Hi Paul,

I had John O'Donnell perform one more set of tests as a "newbie" to Iridium Go and using only the SOPs. The test was very successful but highlighted some required updates to the SOP. I'll work on these ad advise the changes for you to incorporate in your notes.

kind regards
Steven

**Comment by pjwain** [comment]
Hi Steve, Have you got the automatic position reporting going yet? If so
can you give me the link to the map showing Namadgi's position? I would
like to set up the link on the CORC website. Thanks, Peter.

**Comment by smr547** [comment]
Hi Peter, Good thought.... I'll check on that now. Some techical notes for this issue:

* Iridium Go advertises a WiFi HotSpot on board N3
* * SSID: IRIDIUM-21399
* * PASSWORD: corc-062
* Devices connecting to this network will be allocated an IP address on the private network 192.168.0.0/24
* Iridium Go runs a web server available at http://192.168.0.1 which provides status and admin capabilities

I'm working my way through these instructions to ensure tracking is enabled and will let you know when it's working.
@delcosta Sam, please let me know if you have already set this up. 

kind regards
Steven

**Comment by smr547** [comment]
Tracking via Iridium Go and Predict Wind now enabled.  We should advertised the following link to all members

https://forecast.predictwind.com/tracking/display/Namadgi3/

Note: **The Iridium Go unit must be left on at all times for the tracking to continue.** This practice will also give the Committee and operations managers phone and SMS access to Namadgi at all times on +881652450614 and free SMS messaging capability via https://www.predictwind.com/iridium-free-sms/

I'll leave it to the committee to decide how far we promulgate these numbers. @Christopher-w-green might have some recommendations for us. My gut feel is that we should preserve this number for operational use only and discourage private use (by NOT promulgating the number widely). 

I'm not sure of the costs implications of the Iridium Go system or our current subscription -- @pjwain or @delcosta may be able to comment on this. 

[Iridium Go](https://www.iridium.com/products/iridium-go/) combined with [Predict Wind](https://www.predictwind.com/) appears to be a superb system ideally suited for CORC's adventures into the Pacific. From early testing, and contrary to my original opinion, it seems to be working very well. I'm pleasantly surprised!!

Lets keep this issue open while a few more checks are completed.

**Comment by delcosta** [comment]
Steve
I think it was already set up.
I seud that pass to log in at the restart.


Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835<tel:+61%20411%20165%20835>
PO Box 3553, Manuka ACT AUSTRALIA 2603
Sent from my phone



-------- Original message --------
From: Steven Ring ***@***.***>
Date: 21/12/22 12:07 (GMT+10:00)
To: CanberraOceanRacingClub/namadgi3 ***@***.***>
Cc: "Sam Delorenzo (Delorco)" ***@***.***>, Mention ***@***.***>
Subject: Re: [CanberraOceanRacingClub/namadgi3] Annual Iridium Go Checklist (Issue #630)


Hi Peter, Good thought.... I'll check on that now. Some techical notes for this issue:

  *   Iridium Go advertises a WiFi HotSpot on board N3
  *
     *   SSID: IRIDIUM-21399
  *
     *   PASSWORD: corc-062
  *   Devices connecting to this network will be allocated an IP address on the private network 192.168.0.0/24
  *   Iridium Go runs a web server available at http://192.168.0.1 which provides status and admin capabilities

I'm working my way through these instructions to ensure tracking is enabled and will let you know when it's working.
@delcosta<https://github.com/delcosta> Sam, please let me know if you have already set this up.

kind regards
Steven

**Comment by pcbaston** [comment]
Ok, thanks. Not really thinking of CORC activities at present. Having to
deal with train strikes and cold weather.

Paul Baston

**Comment by smr547** [comment]
All functionality tested and working Ok

Skippers need to be advised to keep the Iridium Go turned on at all times

@mrmrmartin @peterottesen could you please insure that this instruction is included in your documents.

@mgrybaitis @Christopher-w-green will be interested

Leaving this issue open for final checks before departure to NZ

**Comment by mrmrmartin** [comment]
Hi Steven I turned the Iridium Go off when I bombed the boat
The instructions on the bomb said turn off all electrical instruments

cheers

**Comment by smr547** [comment]
Hi @mrmrmartin 

Thanks for that Michael -- a good idea. That bomb was very effective!!

The unit has since been turned on. 

@Christopher-w-green -- I was unable to get Iridium Mail working on the Samsung Tablet (nor on my iPhone for that matter). It seemed to be a setup problem.

Could you please have a look at this when you are next on N3. All the other Iridium Go functions appear to be working reliably

**Comment by Christopher-w-green** [comment]
Steven,
What makes you think it's a problem with the setup? It has been working, so
that suggests the setup is ok. Unless somone has been fiddling with the
stored credentials. I found the mail app is a bit unstable and tends to
crash, and the IridiumGo has lost connection to satellites a couple of
times and needed to reboot.

Chris

**Comment by smr547** [comment]
Hi Chris,

It might me a lack of user education (me being the user). Hopefully we can spend some time together in B/Bay before you trip North to sort this out

regards
Steven

**Comment by smr547** [comment]
A number of checks have been recently completed

- [x] Follow [this guide](https://apollosat.com/docs/iridium-go-pre-trip-checklist/) to check the operation of the Iridium Go
- [x] Subscription current
- [x] Subscription renewal scheduled
- [x] SOP up to date (numbers, passwords, procedures)
- [x] Supporting software on Ships Tablet is updated and functioning

I think this issue can be close. Thank you to everyone involved -- especially @delcosta and @Christopher-w-green 

A reminder to @mrmrmartin and crew to

* Check Iridium GO functionality before departure for NZ
* Leave the Iridium GO system on at all times
* Test regularly to ensure operation (see below)
** Suggest you use Iridium GO for *all* daily reports
** Ops Manager should ``confirm receipt`` of each daily report via Iridium GO
** Crew on board should report via SATPHONE if no confirmation is received via Iridium GO
** NEVER simply assume the system is working and that messages are being delivered

As Ops Manager for the crossing @mgrybaitis will be interested. @pauljones17 will be interested.
