### ISSUE TITLE
Satphone annual checklist

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#631]
- [ ] Follow [this guide](https://www.ipinternational.net/wp-content/uploads/2019/10/PM-0816-Rev-04.docx.pdf) to check the operation of the Satphone
- [x] Subscription current
- [ ] Subscription renewal scheduled
- [ ] SOP up to date (numbers, passwords, procedures)
- [ ] Satphone stored in Emergency Grab Bag

**Comment by pcbaston** [comment]
SATPHONE by Inmarsat tested.
Found GPS satellites and provided GPS fix correctly 
Made a phone call to Steven Ring which dropped out, possibly due to moving antenna away from satellite. Follow up test call successful by keeping antenna pointed North. Both calls approx 30 secs each.

SATPHONE in black pelican case in stowage #18 (Grab bag and emergency lights), it is NOT in the yellow grab bag which appears to be full of flares.

Recommend: SATPHONE be charged and stowed in grab bag for each journey offshore.

**Comment by pcbaston** [comment]
Guide is not appropriate to testing SATPHONE.

**Comment by smr547** [comment]
* Satphone tested again. 
* 588 credits available
* expires 19/10/23 -- 
* Diary entry for renewal in Google calendar canberraoceanracingclub@gmail.com
* SatPhone NOT is grab bag

Leaving this issue open until grab bag storage is completed

@mrmrmartin @mgrybaitis @Christopher-w-green will be interested

**Comment by smr547** [comment]
@mrmrmartin and @Christopher-w-green -- I recommend storing the satphone in the grab bag at all times.

Closing this issue
