### ISSUE TITLE
Collect gear from Sydney businesses and return to Namadgi 3 at Batemans Bay

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#641]
Unfortunately Greg Hall has a medical condition and has been unable to collect the safety and other gear from businesses located in Sydney.  We urgently need assistance in collecting this gear and returning it to Namadgi 3 this week (before 23/12/22)

- [ ] Liferaft #559 -- [Survitech, Wetherill Park](https://goo.gl/maps/j4BgZ5FwRFV4k6Vx5) 
- [ ] Lifejackets #524 -- [MOSS Australia, South Winsor](https://goo.gl/maps/d7qwxhfR4tpD4x5a8)
- [ ] Paddles for dinghy #599 -- [Sydney Powerboat Centre, Brookvale](https://goo.gl/maps/ohHkuwDMYxMTMoK39)
- [ ] Storm Jib #531 -- [Hood Sails, Brookvale](https://goo.gl/maps/FscFqxMJHwtTBD7S9)

**Comment by smr547** [comment]
Test message

**Comment by smr547** [comment]
My cousins Robby Nimo and Peter Weiley have kindly offered to house the equipment before it is picked up for transport to Namadgi 3. Their details address
 

7 Roberts Ave
North Manly
[See map](https://goo.gl/maps/wJnofDJhKKRPbeDN9)

Robby: 0414838281
Peter Weiley: 0451838280

@pjwain will be interested

**Comment by smr547** [comment]
Thank you @pjwain for collecting the liferaft and jackets. They, together with new paddles are at my cousin's place at North Manly.  I'll endeavour to collect these by New Years day for delivery to N3

The storm jib has been delivered to the sail bay at CYCA. I'll endeavour to collect it too be it goes missing.

@mrmrmartin @mgrybaitis @pauljones17 @Christopher-w-green will be interested

**Comment by smr547** [comment]
All done
